# Generated by Django 5.1 on 2024-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
