# Generated by Django 5.1 on 2024-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participation',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
