# Generated by Django 5.1 on 2024-09-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0002_participation_presence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='presence',
            new_name='is_present',
        ),
    ]
