# Generated by Django 5.1 on 2024-09-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_rename_presence_participation_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='signed_up',
            field=models.BooleanField(default=False),
        ),
    ]
