# Generated by Django 5.1 on 2025-07-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0004_participation_signed_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
