# Generated by Django 5.1 on 2024-08-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0004_eventmaster_event_master_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmaster',
            name='location',
        ),
    ]
