# Generated by Django 5.1 on 2024-08-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0005_remove_eventmaster_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
