# Generated by Django 5.1 on 2024-08-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0007_event_duration_event_photo_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
