# Generated by Django 5.1 on 2024-09-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0008_event_event_type_alter_event_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
