# Generated by Django 5.1 on 2024-09-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0009_delete_participation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMaster',
            new_name='EventGroup',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='master_event',
            new_name='group',
        ),
    ]
