# Generated by Django 5.1 on 2024-09-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0010_rename_eventmaster_eventgroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group',
            new_name='main_group',
        ),
    ]
