# Generated by Django 5.1 on 2024-09-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0011_rename_group_event_main_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
