# Generated by Django 5.1 on 2024-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0012_event_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
