# Generated by Django 5.1 on 2024-09-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0013_event_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
    ]
