# Generated by Django 5.1 on 2024-09-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0014_rename_event_type_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='kind',
        ),
    ]
