# Generated by Django 5.1 on 2024-10-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0015_rename_type_event_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDepartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='main_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='events_manager.eventgroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departaments', to='events_manager.eventdepartament'),
        ),
    ]
