# Generated by Django 5.1 on 2025-01-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0001_initial'),
        ('events_manager', '0016_eventdepartament_alter_event_main_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departaments', to='departaments.departament'),
        ),
        migrations.DeleteModel(
            name='EventDepartament',
        ),
    ]
