# Generated by Django 5.1 on 2025-07-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0018_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
